name: Android Build (Fixed)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用旧版系统确保兼容性

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1  # 指定精确版本

    - name: Setup Java 8
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '8'
        distribution: 'zulu'  # 更兼容旧版

    # 修复Flutter安装步骤
    - name: Install Flutter 2.16.1
      uses: subosito/flutter-action@a0b9121667f48c4d4f5fcfebafd8c42e00e3f3c6  # 使用commit hash
      with:
        flutter-version: '2.16.1'
        channel: 'stable'

    - name: Build APK
      run: |
        flutter pub get
        flutter build apk --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
