name: Android Build (Flutter 2.16.1)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用旧版系统确保兼容性
    env:
      FLUTTER_VERSION: "2.16.1"  # 严格锁定版本

    steps:
    - uses: actions/checkout@v4

    # Java 8 环境配置
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    # Flutter 2.16.1 专用配置
    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    # 安卓构建环境准备
    - name: Pre-build setup
      run: |
        flutter doctor -v
        yes | sdkmanager "platforms;android-32"  # 根据项目需求调整
        yes | sdkmanager "build-tools;31.0.0"

    # 项目构建流程
    - name: Build APK
      run: |
        flutter pub get
        flutter build apk --release

    - uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
