name: Build Android APK

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment to run the workflow

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.16.1'  # Ensure you're using a compatible Flutter version

      # Step 3: Set up Java 8
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adoptopenjdk'

      # Step 4: Set up Android SDK (necessary for building Android apps)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: 'commandlinetools-linux-8512546_latest'
          target: android-30
          modules: 'platform-tools,build-tools;30.0.3'

      # Step 5: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 6: Build APK (release version)
      - name: Build APK
        run: flutter build apk --release

      # Step 7: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
